networks:
  homelab:
    driver: bridge

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Toronto
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - homelab

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80"  # Pi-hole admin interface
    environment:
      TZ: "America/Toronto"
      WEBPASSWORD: "changeme"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - homelab
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - homelab
    ports:
      - "9100:9100"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - homelab
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    restart: unless-stopped

  jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      networks:
        - homelab
      environment:
        - LOG_LEVEL=debug
        - TZ=America/Toronto
        - PORT=5055 #optional
      ports:
        - 5055:5055
      volumes:
        - ~/docker/jellyseerr:/app/config
      healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
        start_period: 20s
        timeout: 3s
        interval: 15s
        retries: 3
      restart: unless-stopped